# Generated by Django 4.0.5 on 2022-12-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tempuser_f_id_alter_tempuser_d_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.device'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='d_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.alldevices'),
        ),
    ]
