# Generated by Django 4.0.5 on 2022-12-14 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tempuser_device_alter_tempuser_d_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='status1',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
