# Generated by Django 4.0.5 on 2022-12-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tempuser_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempuser',
            old_name='status1',
            new_name='status',
        ),
    ]
