# Generated by Django 4.1.4 on 2022-12-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_ssidpassword_emergencynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='pinschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-01-01', null=True)),
                ('timing', models.CharField(default='00:00', max_length=200)),
                ('pin1Status', models.IntegerField(blank=True, null=True)),
                ('pin2Status', models.IntegerField(blank=True, null=True)),
                ('pin3Status', models.IntegerField(blank=True, null=True)),
                ('pin4Status', models.IntegerField(blank=True, null=True)),
                ('pin5Status', models.IntegerField(blank=True, null=True)),
                ('pin6Status', models.IntegerField(blank=True, null=True)),
                ('pin7Status', models.IntegerField(blank=True, null=True)),
                ('pin8Status', models.IntegerField(blank=True, null=True)),
                ('pin9Status', models.IntegerField(blank=True, null=True)),
                ('pin10Status', models.IntegerField(blank=True, null=True)),
                ('pin11Status', models.IntegerField(blank=True, null=True)),
                ('pin12Status', models.IntegerField(blank=True, null=True)),
                ('pin13Status', models.IntegerField(blank=True, null=True)),
                ('pin14Status', models.IntegerField(blank=True, null=True)),
                ('pin15Status', models.IntegerField(blank=True, null=True)),
                ('pin16Status', models.IntegerField(blank=True, null=True)),
                ('pin17Status', models.BigIntegerField(blank=True, null=True)),
                ('pin18Status', models.IntegerField(blank=True, null=True)),
                ('pin19Status', models.CharField(blank=True, max_length=100, null=True)),
                ('pin20Status', models.CharField(blank=True, max_length=100, null=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.alldevices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
