# Generated by Django 4.1.4 on 2022-12-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pinschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='status',
        ),
    ]
