# Generated by Django 4.1.4 on 2022-12-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_tempuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='device',
        ),
    ]
