# Generated by Django 4.1.4 on 2022-12-28 11:03

from django.db import migrations, models
import myapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_tempuser_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempUserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, default=myapp.utils.otplogin, max_length=6)),
            ],
        ),
    ]
