# Generated by Django 4.1.5 on 2023-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tempuserverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='exl_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exl_file', models.CharField(max_length=10)),
            ],
        ),
    ]
